<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Investigation Report #{{ $log->id }}</title>

<style>
  @page {
    margin: 80px 1cm 60px 1cm;
    size: A4;
  }

  body {
    font-family: Helvetica, Arial, sans-serif;
    color: #0f172a;
    background: #ffffff;
    font-size: 9.2pt;
    margin: 0; padding: 0;
    line-height: 1.55;
  }

  .text-center { text-align: center; }
  .text-right { text-align: right; }
  .text-muted { color: #64748b; }
  .text-blue { color: #2563eb; }
  .text-red { color: #dc2626; }
  .text-green { color: #16a34a; }
  .font-bold { font-weight: 700; }
  .font-mono { font-family: "Courier New", Courier, monospace; }
  .uppercase { text-transform: uppercase; letter-spacing: .04em; }
  .avoid-break { page-break-inside: avoid; }

  .page-break {
    page-break-after: always;
    height: 0 !important;
    margin: 0 !important; padding: 0 !important; border: 0 !important;
  }

  .divider { height: 1px; background: #e2e8f0; margin: 12px 0; }

  header {
    position: fixed;
    left: 0; right: 0;
    top: -60px;
    height: 35px;
    border-bottom: 2px solid #2563eb;
    text-align: right;
    font-size: 7pt;
    color: #94a3b8;
    padding-top: 10px;
  }

  footer {
    position: fixed;
    left: 0; right: 0;
    bottom: -45px;
    height: 30px;
    border-top: 1px solid #e2e8f0;
    text-align: center;
    font-size: 7.5pt;
    color: #94a3b8;
    padding-top: 8px;
  }

  .card {
    background: #ffffff;
    border: 1px solid #e2e8f0;
    border-radius: 10px;
    padding: 16px 18px;
    margin-bottom: 14px;
  }

  .card-header {
    font-size: 10.5pt;
    font-weight: 800;
    color: #0f172a;
    padding-bottom: 10px;
    margin-bottom: 12px;
    border-bottom: 1px solid #f1f5f9;
  }

  .badge {
    display: inline-block;
    padding: 3px 10px;
    border-radius: 9999px;
    font-size: 7.5pt;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: .04em;
    white-space: nowrap;
  }
  .badge-red { background: #fee2e2; color: #991b1b; }
  .badge-green { background: #dcfce7; color: #166534; }
  .badge-blue { background: #dbeafe; color: #1e40af; }
  .badge-gray { background: #f1f5f9; color: #475569; }
  .badge-orange { background: #ffedd5; color: #9a3412; }
  .badge-amber { background: #fef3c7; color: #92400e; }

  table.grid { width: 100%; border-collapse: collapse; }
  table.grid td { vertical-align: top; padding: 0; }
  .col-gap { width: 14px; }
  .col-50 { width: 50%; }
  .col-30 { width: 30%; }
  .col-70 { width: 70%; }

  table.detail-table { width: 100%; border-collapse: collapse; }
  table.detail-table td { padding: 8px 10px; border-bottom: 1px solid #f1f5f9; vertical-align: top; }
  table.detail-table .label { width: 130px; color: #64748b; font-size: 8pt; font-weight: 700; text-transform: uppercase; letter-spacing: .04em; }
  table.detail-table .value { color: #0f172a; font-size: 9.5pt; }

  .metric {
    text-align: center;
    padding: 12px 10px;
    background: #f8fafc;
    border: 1px solid #eef2f7;
    border-radius: 10px;
  }
  .metric-value { font-size: 16pt; font-weight: 900; color: #0f172a; line-height: 1.1; }
  .metric-label { font-size: 7.5pt; color: #64748b; text-transform: uppercase; letter-spacing: .05em; margin-top: 4px; }

  /* Cover */
  .cover { padding: 2cm 1.4cm 1.6cm 1.4cm; }
  .logo-img { height: 60px; margin-bottom: 16px; }
  .report-title { font-size: 22pt; font-weight: 900; color: #0f172a; letter-spacing: -.5px; margin-bottom: 6px; }
  .report-subtitle { font-size: 11pt; color: #64748b; margin-bottom: 16px; }

  .cover-box {
    margin: 20px auto 0 auto;
    width: 90%;
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 14px;
    padding: 16px;
  }
  .cover-label { font-weight: 800; color: #94a3b8; font-size: 8pt; text-transform: uppercase; letter-spacing: .05em; display: block; margin-bottom: 3px; }
  .cover-value { font-size: 10pt; color: #0f172a; font-weight: 700; }

  /* Timeline */
  .timeline-item {
    padding: 10px 12px;
    margin-bottom: 8px;
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-left: 3px solid #2563eb;
    border-radius: 6px;
  }
  .timeline-date { font-size: 8pt; color: #94a3b8; font-family: "Courier New", monospace; }
  .timeline-action { font-size: 9.5pt; font-weight: 700; color: #0f172a; margin-top: 2px; }
  .timeline-desc { font-size: 9pt; color: #475569; margin-top: 3px; }
  .timeline-user { font-size: 7.5pt; color: #94a3b8; margin-top: 4px; }
</style>
</head>

<body>
<header>
    CONFIDENTIAL // INVESTIGATION REPORT // INV-{{ str_pad($log->id, 4, '0', STR_PAD_LEFT) }}
</header>
<footer>
    Page <span class="page-number"></span> | Generated by Security Operations System — {{ now()->timezone('Asia/Jakarta')->format('d M Y, H:i') }} WIB
</footer>

<div class="container">

    <!-- COVER PAGE -->
    <div class="cover avoid-break">
        <div class="text-center">
            <img src="{{ public_path('images/mega-insurance-logo.png') }}" class="logo-img" alt="Mega Insurance" style="padding:10px 0;">
            @if($log->status === 'In Progress')
            <div class="report-title" style="color:#d97706;">Ongoing Investigation Report</div>
            <div class="report-subtitle">Security Incident Under Active Investigation</div>
            @else
            <div class="report-title">Investigation Report</div>
            <div class="report-subtitle">Security Incident Closure & Management Summary</div>
            @endif
        </div>

        <div class="cover-box">
            <table style="width:100%; border-collapse:collapse;">
                <tr>
                    <td style="padding:6px;">
                        <span class="cover-label">Case ID</span>
                        <div class="cover-value font-mono">INV-{{ str_pad($log->id, 4, '0', STR_PAD_LEFT) }}</div>
                    </td>
                    <td style="padding:6px;">
                        <span class="cover-label">Incident Type</span>
                        <div class="cover-value">
                            @if($log->type === 'Email Phishing')
                                <span class="badge badge-orange">Email Phishing</span>
                            @elseif($log->type === 'File Check')
                                <span class="badge badge-green" style="background:#ccfbf1; color:#0f766e;">File Check</span>
                            @elseif($log->type === 'Domain Check')
                                <span class="badge badge-blue" style="background:#f3e8ff; color:#7e22ce;">Domain Check</span>
                            @else
                                <span class="badge badge-blue">SIEM Incident</span>
                            @endif
                        </div>
                    </td>
                </tr>
                <tr>
                    <td style="padding:6px;">
                        <span class="cover-label">Date Filed</span>
                        <div class="cover-value">{{ ($log->mitigated_at ?? $log->created_at)->timezone('Asia/Jakarta')->format('d M Y, H:i') }} WIB</div>
                    </td>
                    <td style="padding:6px;">
                        <span class="cover-label">Status</span>
                        @if($log->status === 'In Progress')
                        <span class="badge badge-amber" style="font-size:8.5pt;">🔵 IN PROGRESS</span>
                        @else
                        <span class="badge badge-green" style="font-size:8.5pt;">RESOLVED & VERIFIED</span>
                        @endif
                    </td>
                </tr>
                @if($log->incident_time)
                <tr>
                    <td style="padding:6px;">
                        <span class="cover-label">Incident Time</span>
                        <div class="cover-value">{{ \Carbon\Carbon::parse($log->incident_time)->timezone('Asia/Jakarta')->format('d M Y, H:i') }} WIB</div>
                    </td>
                    <td style="padding:6px;">
                        @if($log->attack_classification)
                        <span class="cover-label">Classification</span>
                        <div class="cover-value">
                            @if($log->attack_classification === 'True Attack')
                                <span class="badge badge-red" style="background:#fee2e2;color:#dc2626;">🔴 True Attack</span>
                            @else
                                <span class="badge badge-green">🟢 False Attack</span>
                            @endif
                        </div>
                        @endif
                    </td>
                </tr>
                @endif
                <tr>
                    <td style="padding:6px;">
                        <span class="cover-label">Investigator</span>
                        <div class="cover-value">{{ $log->user->name ?? 'Unknown' }}</div>
                    </td>
                    <td style="padding:6px;">
                        <span class="cover-label">Report Generated</span>
                        <div class="cover-value">{{ now()->timezone('Asia/Jakarta')->format('d M Y') }}</div>
                    </td>
                </tr>
            </table>
        </div>

        <div class="text-center" style="margin-top:30px; color:#94a3b8; font-size:9pt;">
            <div class="uppercase font-bold">PT ASURANSI UMUM MEGA</div>
            <div class="text-muted">Security Operations Center</div>
        </div>
    </div>

    <div class="page-break"></div>

    <!-- 1. INVESTIGATION SUMMARY -->
    <div class="card">
        <div class="card-header">1. Investigation Summary</div>

        <table class="detail-table">
            <tr>
                <td class="label">Title</td>
                <td class="value font-bold">{{ $log->title }}</td>
            </tr>
            <tr>
                <td class="label">Description</td>
                <td class="value">{!! nl2br(e($log->description)) !!}</td>
            </tr>
            @if($log->analyst_decision)
            <tr>
                <td class="label">Analyst Decision</td>
                <td class="value" style="background-color:#f0f9ff; border:1px solid #bae6fd; border-radius:6px; padding:10px;">
                    <div style="font-weight:bold; color:#0369a1; margin-bottom:4px; font-size:8pt; text-transform:uppercase; letter-spacing:.05em;">Analysis Conslusion</div>
                    <div style="color:#0c4a6e;">{!! nl2br(e($log->analyst_decision)) !!}</div>
                </td>
            </tr>
            @endif
            <tr>
                <td class="label">Incident Type</td>
                <td class="value">
                    @if($log->type === 'Email Phishing')
                        <span class="badge badge-orange">Email Phishing</span>
                    @elseif($log->type === 'File Check')
                        <span class="badge badge-green" style="background:#ccfbf1; color:#0f766e;">File Check</span>
                    @elseif($log->type === 'Domain Check')
                        <span class="badge badge-blue" style="background:#f3e8ff; color:#7e22ce;">Domain Check</span>
                    @else
                        <span class="badge badge-blue">SIEM Incident</span>
                    @endif
                </td>
            </tr>
            @if($log->attack_classification)
            <tr>
                <td class="label">Classification</td>
                <td class="value">
                    @if($log->attack_classification === 'True Attack')
                        <span class="badge badge-red" style="background:#fee2e2;color:#dc2626;">🔴 True Attack</span>
                    @else
                        <span class="badge badge-green">🟢 False Attack</span>
                    @endif
                </td>
            </tr>
            @endif
            @if($log->incident_time)
            <tr>
                <td class="label">Incident Time</td>
                <td class="value">{{ \Carbon\Carbon::parse($log->incident_time)->timezone('Asia/Jakarta')->format('d M Y, H:i') }} WIB</td>
            </tr>
            @endif

            <!-- Specific Fields -->
            @if($log->type === 'File Check' && $log->fileAnalysis)
            <tr>
                <td class="label">File Name</td>
                <td class="value font-mono">{{ $log->fileAnalysis->file_name }}</td>
            </tr>
            <tr>
                <td class="label">File Hash</td>
                <td class="value font-mono" style="font-size:8pt;">{{ $log->fileAnalysis->file_hash_sha256 }}</td>
            </tr>
            @endif

            @if($log->type === 'Domain Check' && $log->urlAnalysis)
            <tr>
                <td class="label">Analyzed URL</td>
                <td class="value font-mono" style="word-break:break-all;">{{ $log->urlAnalysis->url }}</td>
            </tr>
            @endif

            @if($log->type !== 'Email Phishing' && $log->system_affected)
            <tr>
                <td class="label">System Affected</td>
                <td class="value font-mono">{{ $log->system_affected }}</td>
            </tr>
            @endif

            @if(in_array($log->type, ['Email Phishing', 'File Check', 'Domain Check']) && $log->reporter_email)
            <tr>
                <td class="label">Reported By</td>
                <td class="value">{{ $log->reporter_email }}</td>
            </tr>
            @endif
            @if(in_array($log->type, ['Email Phishing', 'File Check', 'Domain Check']) && $log->reporter_department)
            <tr>
                <td class="label">Department</td>
                <td class="value">{{ $log->reporter_department }}</td>
            </tr>
            @endif

            <tr>
                <td class="label">Logged By</td>
                <td class="value">{{ $log->user->name ?? 'Unknown' }}</td>
            </tr>
            <tr>
                <td class="label">Date Filed</td>
                <td class="value">{{ $log->mitigated_at->timezone('Asia/Jakarta')->format('d M Y, H:i') }} WIB</td>
            </tr>
            <tr>
                <td class="label">Date Resolved</td>
                <td class="value">{{ $log->updated_at->timezone('Asia/Jakarta')->format('d M Y, H:i') }} WIB</td>
            </tr>
            <tr>
                <td class="label">Resolution Time</td>
                <td class="value font-bold">{{ $log->mitigated_at->diffForHumans($log->updated_at, ['parts' => 2, 'short' => true]) }}</td>
            </tr>
            <tr>
                <td class="label">Final Status</td>
                <td class="value"><span class="badge badge-green">Resolved & Verified</span></td>
            </tr>
        </table>
    </div>

    <!-- 2. DETAILS SECTIONS -->
    
    <!-- A. PHISHING DETAILS -->
    @if($log->type === 'Email Phishing')
    <div class="card" style="border-left: 3px solid #f59e0b;">
        <div class="card-header">2. Phishing Incident Details</div>

        <table class="detail-table">
            <tr>
                <td class="label">Email Subject</td>
                <td class="value font-bold">{{ $log->email_subject }}</td>
            </tr>
            <tr>
                <td class="label">Sender</td>
                <td class="value font-mono text-red">{{ $log->email_sender }}</td>
            </tr>
            <tr>
                <td class="label">Recipient</td>
                <td class="value font-mono">{{ $log->email_recipient }}</td>
            </tr>
            @if($log->email_headers)
            <tr>
                <td class="label">Email Headers</td>
                <td class="value" style="font-size:7.5pt; font-family:monospace; word-break:break-all;">{{ Illuminate\Support\Str::limit($log->email_headers, 500) }}</td>
            </tr>
            @endif
        </table>

    </div>

    <!-- C. FILE ANALYSIS DETAILS -->
    @elseif($log->type === 'File Check' && $log->fileAnalysis)
    <div class="card" style="border-left: 3px solid #0f766e;">
        <div class="card-header">2. File Analysis Details</div>

        @php
            $res = $log->fileAnalysis->result['attributes'] ?? $log->fileAnalysis->result ?? [];
            $stats = $res['last_analysis_stats'] ?? $res['stats'] ?? ['malicious'=>0,'suspicious'=>0,'harmless'=>0,'undetected'=>0];
            $malicious = $stats['malicious'] ?? 0;
            $suspicious = $stats['suspicious'] ?? 0;
            $harmless = $stats['harmless'] ?? 0;
            $undetected = $stats['undetected'] ?? 0;
            $total = array_sum($stats);
        @endphp

        <table class="detail-table">
            <tr>
                <td class="label">Analyzed File</td>
                <td class="value font-bold">{{ $log->fileAnalysis->file_name }}</td>
            </tr>
            <tr>
                <td class="label">Threat Verdict</td>
                <td class="value">
                    @if($malicious > 0)
                        <span class="badge badge-red">MALICIOUS DETECTED ({{ $malicious }}/{{ $total }})</span>
                    @else
                        <span class="badge badge-green">CLEAN (0/{{ $total }})</span>
                    @endif
                </td>
            </tr>
            <tr>
                <td class="label">SHA-256 Hash</td>
                <td class="value font-mono" style="font-size:8pt; word-break:break-all;">{{ $log->fileAnalysis->file_hash_sha256 }}</td>
            </tr>
        </table>

        <div style="margin-top:15px; background:#f8fafc; padding:15px; border-radius:8px; border:1px solid #f1f5f9;">
            <div class="uppercase font-bold" style="font-size:8pt; color:#64748b; margin-bottom:10px;">Security Vendor Detection Stats</div>
            <table style="width:100%; text-align:center;">
                <tr>
                    <td class="metric" style="width:25%; border-color:#fee2e2; background:#fef2f2;">
                        <div class="metric-value text-red">{{ $malicious }}</div>
                        <div class="metric-label text-red">Malicious</div>
                    </td>
                    <td style="width:10px;"></td>
                    <td class="metric" style="width:25%; border-color:#ffedd5; background:#fff7ed;">
                        <div class="metric-value" style="color:#c2410c;">{{ $suspicious }}</div>
                        <div class="metric-label" style="color:#c2410c;">Suspicious</div>
                    </td>
                    <td style="width:10px;"></td>
                    <td class="metric" style="width:25%; border-color:#dcfce7; background:#f0fdf4;">
                        <div class="metric-value text-green">{{ $harmless }}</div>
                        <div class="metric-label text-green">Clean</div>
                    </td>
                    <td style="width:10px;"></td>
                    <td class="metric" style="width:25%; border-color:#f1f5f9; background:#f8fafc;">
                        <div class="metric-value text-muted">{{ $undetected }}</div>
                        <div class="metric-label text-muted">Undetected</div>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <!-- C. DOMAIN ANALYSIS DETAILS -->
    @elseif($log->type === 'Domain Check' && $log->urlAnalysis)
    <div class="card" style="border-left: 3px solid #7e22ce;">
        <div class="card-header">2. Domain/URL Analysis Details</div>

        @php
            $res = $log->urlAnalysis->result['attributes'] ?? $log->urlAnalysis->result ?? [];
            $stats = $res['last_analysis_stats'] ?? $res['stats'] ?? ['malicious'=>0,'suspicious'=>0,'harmless'=>0,'undetected'=>0];
            $malicious = $stats['malicious'] ?? 0;
            $suspicious = $stats['suspicious'] ?? 0;
            $harmless = $stats['harmless'] ?? 0;
            $undetected = $stats['undetected'] ?? 0;
            $total = array_sum($stats);
        @endphp

        <table class="detail-table">
            <tr>
                <td class="label">Analyzed URL</td>
                <td class="value font-bold font-mono" style="word-break:break-all;">{{ $log->urlAnalysis->url }}</td>
            </tr>
            <tr>
                <td class="label">Threat Verdict</td>
                <td class="value">
                    @if($malicious > 0)
                        <span class="badge badge-red">MALICIOUS DETECTED ({{ $malicious }}/{{ $total }})</span>
                    @else
                        <span class="badge badge-green">CLEAN (0/{{ $total }})</span>
                    @endif
                </td>
            </tr>
        </table>

         <div style="margin-top:15px; background:#f8fafc; padding:15px; border-radius:8px; border:1px solid #f1f5f9;">
            <div class="uppercase font-bold" style="font-size:8pt; color:#64748b; margin-bottom:10px;">Security Vendor Detection Stats</div>
            <table style="width:100%; text-align:center;">
                <tr>
                    <td class="metric" style="width:25%; border-color:#fee2e2; background:#fef2f2;">
                        <div class="metric-value text-red">{{ $malicious }}</div>
                        <div class="metric-label text-red">Malicious</div>
                    </td>
                    <td style="width:10px;"></td>
                    <td class="metric" style="width:25%; border-color:#ffedd5; background:#fff7ed;">
                        <div class="metric-value" style="color:#c2410c;">{{ $suspicious }}</div>
                        <div class="metric-label" style="color:#c2410c;">Suspicious</div>
                    </td>
                    <td style="width:10px;"></td>
                    <td class="metric" style="width:25%; border-color:#dcfce7; background:#f0fdf4;">
                        <div class="metric-value text-green">{{ $harmless }}</div>
                        <div class="metric-label text-green">Clean</div>
                    </td>
                    <td style="width:10px;"></td>
                    <td class="metric" style="width:25%; border-color:#f1f5f9; background:#f8fafc;">
                        <div class="metric-value text-muted">{{ $undetected }}</div>
                        <div class="metric-label text-muted">Undetected</div>
                    </td>
            </table>
        </div>
    </div>
    @endif
    <!-- IP ANALYZER RESULT -->
    @if($log->ipAnalysis)
    @php
        $ipData = $log->ipAnalysis;
        $riskScore = $ipData->risk_score ?? 0;
        $geo = $ipData->geo_data ?? [];
        $abuse = $ipData->abuseipdb_data ?? [];
        $vt = $ipData->virustotal_data ?? [];
        $vtStats = $vt['last_analysis_stats'] ?? $vt['stats'] ?? null;
        $abuseConf = $abuse['abuseConfidenceScore'] ?? $abuse['confidence_score'] ?? null;
    @endphp
    <div class="card avoid-break">
        <div class="card-header">IP Analyzer Result</div>
        <table style="width:100%; margin-bottom:10px;">
            <tr>
                <td class="metric" style="width:25%; border-color:{{ $riskScore >= 70 ? '#fecaca' : ($riskScore >= 40 ? '#fef3c7' : '#dcfce7') }}; background:{{ $riskScore >= 70 ? '#fef2f2' : ($riskScore >= 40 ? '#fffbeb' : '#f0fdf4') }};">
                    <div class="metric-value" style="color:{{ $riskScore >= 70 ? '#dc2626' : ($riskScore >= 40 ? '#d97706' : '#16a34a') }};">{{ $riskScore }}/100</div>
                    <div class="metric-label" style="color:{{ $riskScore >= 70 ? '#dc2626' : ($riskScore >= 40 ? '#d97706' : '#16a34a') }};">Risk Score</div>
                </td>
                <td style="width:10px;"></td>
                <td class="metric" style="width:25%; border-color:#e2e8f0; background:#f8fafc;">
                    <div class="metric-value text-muted" style="font-size:11pt;">{{ $ipData->ip_address }}</div>
                    <div class="metric-label text-muted">IP Address</div>
                </td>
                <td style="width:10px;"></td>
                <td class="metric" style="width:20%; border-color:#e2e8f0; background:#f8fafc;">
                    <div class="metric-value text-muted" style="font-size:11pt;">{{ $geo['country'] ?? $geo['country_name'] ?? '-' }}</div>
                    <div class="metric-label text-muted">Country</div>
                </td>
                <td style="width:10px;"></td>
                <td class="metric" style="width:20%; border-color:#e2e8f0; background:#f8fafc;">
                    <div class="metric-value text-muted" style="font-size:11pt;">{{ $abuseConf !== null ? $abuseConf . '%' : '-' }}</div>
                    <div class="metric-label text-muted">AbuseIPDB</div>
                </td>
            </tr>
        </table>
        <table style="width:100%; font-size:8.5pt; border-collapse:collapse;">
            <tr>
                <td style="padding:6px 10px; border-bottom:1px solid #e2e8f0; color:#64748b; width:35%;">ISP / Organization</td>
                <td style="padding:6px 10px; border-bottom:1px solid #e2e8f0; color:#1e293b;">{{ $geo['isp'] ?? $geo['org'] ?? '-' }}</td>
            </tr>
            @if($vtStats)
            <tr>
                <td style="padding:6px 10px; border-bottom:1px solid #e2e8f0; color:#64748b;">VirusTotal Detection</td>
                <td style="padding:6px 10px; border-bottom:1px solid #e2e8f0;">
                    <span style="color:#dc2626; font-weight:600;">Malicious: {{ $vtStats['malicious'] ?? 0 }}</span> &nbsp;&bull;&nbsp;
                    <span style="color:#d97706; font-weight:600;">Suspicious: {{ $vtStats['suspicious'] ?? 0 }}</span> &nbsp;&bull;&nbsp;
                    <span style="color:#16a34a;">Clean: {{ $vtStats['harmless'] ?? 0 }}</span> &nbsp;&bull;&nbsp;
                    <span style="color:#94a3b8;">Undetected: {{ $vtStats['undetected'] ?? 0 }}</span>
                </td>
            </tr>
            @endif
        </table>
    </div>
    @endif

    <!-- ATTACHED EVIDENCE (ALL TYPES) -->
    @if($log->files->count() > 0)
    <div class="card avoid-break">
        <div class="card-header">Attached Evidence ({{ $log->files->count() }})</div>
        @foreach($log->files as $file)
            @php
                $ext = strtolower(pathinfo($file->original_name, PATHINFO_EXTENSION));
                $isImage = in_array($ext, ['jpg','jpeg','png','gif','webp']);
                $filePath = storage_path('app/public/' . $file->file_path);
                if (!file_exists($filePath)) {
                    $filePath = public_path('storage/' . $file->file_path);
                }
            @endphp
            <div style="margin-bottom:14px; page-break-inside:avoid;">
                <div style="font-size:8pt; color:#64748b; margin-bottom:4px;">
                    <span class="font-bold">{{ $file->original_name }}</span> — {{ number_format($file->file_size / 1024, 1) }} KB
                </div>
                @if($isImage && file_exists($filePath))
                    <div style="text-align:center; padding:8px; background:#f8fafc; border:1px solid #e2e8f0; border-radius:6px;">
                        <img src="{{ $filePath }}" style="max-width:100%; max-height:400px; border-radius:4px;">
                    </div>
                @else
                    <div style="padding:8px 12px; background:#f1f5f9; border:1px solid #e2e8f0; border-radius:6px; font-size:8pt; color:#475569;">
                        <i>File type ({{ strtoupper($ext) }}) — not previewable in PDF</i>
                    </div>
                @endif
            </div>
        @endforeach
    </div>
    @endif

    <!-- 3. EVENT LOG / RAW EVIDENCE -->
    @if($log->event_log)
    <div class="card avoid-break">
        <div class="card-header">{{ in_array($log->type, ['Email Phishing', 'File Check', 'Domain Check']) ? '3' : '2' }}. Event Log / Evidence</div>
        <div style="background:#1e293b; color:#a5f3fc; padding:12px 14px; border-radius:8px; font-family:'Courier New',monospace; font-size:8pt; line-height:1.5; word-break:break-all;">
            {{ Illuminate\Support\Str::limit($log->event_log, 2000) }}
        </div>
    </div>
    @endif

    <!-- 4. INVESTIGATION TIMELINE -->
    @if($log->details->count() > 0)
    <div class="card">
        @php
            $sectionNum = 2;
            if (in_array($log->type, ['Email Phishing', 'File Check', 'Domain Check'])) $sectionNum = 3;
            if ($log->event_log) $sectionNum++;
        @endphp
        <div class="card-header">{{ $sectionNum + 1 }}. Investigation Timeline ({{ $log->details->count() }} entries)</div>

        @foreach($log->details as $detail)
        <div class="timeline-item avoid-break">
            <div class="timeline-date">{{ $detail->log_date->timezone('Asia/Jakarta')->format('d M Y, H:i') }} WIB</div>
            <div class="timeline-action">{{ $detail->action }}</div>
            <div class="timeline-desc">{{ $detail->description }}</div>
            <div class="timeline-user">— {{ $detail->user->name ?? 'System' }}</div>
        </div>
        @endforeach
    </div>
    @endif

    <!-- VISUAL EVIDENCE SECTION -->
    @if($log->type !== 'Email Phishing' && ($log->evidence_before || $log->evidence_after))
    <div class="card avoid-break">
        <div class="card-header">Visual Evidence</div>

        <table class="grid">
            <tr>
                @if($log->evidence_before)
                <td class="col-50">
                    <div class="uppercase font-bold text-muted" style="font-size:7.5pt; margin-bottom:6px;">Before Mitigation</div>
                    @php
                        $ext = strtolower(pathinfo($log->evidence_before, PATHINFO_EXTENSION));
                        $isImage = in_array($ext, ['jpg','jpeg','png','gif','webp']);
                        $path = storage_path('app/public/' . $log->evidence_before);
                        if (!file_exists($path)) $path = public_path('storage/' . $log->evidence_before);
                    @endphp
                    @if($isImage && file_exists($path))
                        <img src="{{ $path }}" style="max-width:100%; border:1px solid #e2e8f0; border-radius:6px;">
                    @else
                        <div style="background:#f1f5f9; padding:10px; border-radius:6px; font-size:8pt; color:#64748b;">File: {{ basename($log->evidence_before) }}</div>
                    @endif
                </td>
                <td class="col-gap"></td>
                @endif
                @if($log->evidence_after)
                <td class="{{ $log->evidence_before ? 'col-50' : '' }}">
                    <div class="uppercase font-bold" style="font-size:7.5pt; color:#16a34a; margin-bottom:6px;">After Mitigation</div>
                    @php
                        $ext = strtolower(pathinfo($log->evidence_after, PATHINFO_EXTENSION));
                        $isImage = in_array($ext, ['jpg','jpeg','png','gif','webp']);
                        $path = storage_path('app/public/' . $log->evidence_after);
                        if (!file_exists($path)) $path = public_path('storage/' . $log->evidence_after);
                    @endphp
                    @if($isImage && file_exists($path))
                        <img src="{{ $path }}" style="max-width:100%; border:1px solid #dcfce7; border-radius:6px;">
                    @else
                        <div style="background:#f0fdf4; padding:10px; border-radius:6px; font-size:8pt; color:#16a34a;">File: {{ basename($log->evidence_after) }}</div>
                    @endif
                </td>
                @endif
            </tr>
        </table>
    </div>
    @endif

    <!-- SIGN-OFF -->
    <div class="card avoid-break" style="margin-top:20px; border-top:3px solid #2563eb;">
        <div class="text-center" style="padding:10px 0;">
            <div class="font-bold" style="font-size:10pt; color:#0f172a;">Investigation Closed</div>
            <div class="text-muted" style="font-size:9pt; margin-top:4px;">
                This incident has been resolved and verified by the Security Operations team.
            </div>
            <div style="margin-top:20px;">
                <table style="width:80%; margin:0 auto; border-collapse:collapse;">
                    <tr>
                        <td style="padding:6px; text-align:center;">
                            <div style="border-top:1px solid #cbd5e1; margin-top:30px; padding-top:6px;">
                                <div class="font-bold" style="font-size:9pt;">Tengku Arya Saputra</div>
                                <div class="text-muted" style="font-size:7.5pt;">IT Security & Governance Analyst</div>
                            </div>
                        </td>
                        <td style="padding:6px; text-align:center;">
                            <div style="border-top:1px solid #cbd5e1; margin-top:30px; padding-top:6px;">
                                <div class="font-bold" style="font-size:9pt;">Wilson</div>
                                <div class="text-muted" style="font-size:7.5pt;">IT QA, Security & Governance Department Head</div>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="text-muted" style="margin-top:20px; font-size:7.5pt;">
                Report generated on {{ now()->timezone('Asia/Jakarta')->format('d M Y, H:i') }} WIB — Security Operations Center, PT Asuransi Umum Mega
            </div>
        </div>
    </div>

</div>
</body>
</html>
